FERNET_KEY = "cVjDVe62vqCkmqPwvDZcTxVPuedyYt4pVQnXsnRf6KA="
INDEX_KEY = "000102030405060708090A0B0C0D0E0F000102030405060708090A0B0C0D0E0F"
CYBORGDB_API_KEY = "cyborg_9e0a3d56d0624ee2a8d2acc9d1f4a5f3"
CYBORGDB_ENDPOINT = "http://localhost:8000"


